"""family_reports: monthly per-elder status-and-trends report

Revision ID: 0025
Revises: 0024
Create Date: 2026-06-15

US8 / T077. One row per elder per calendar month (unique ``(elder_id, period_month)`` =>
once-per-month idempotent, FR-012 / SC-012). ``metrics``/``narrative`` hold the PHI trend
detail (stay in BAA Postgres); ``sms_message_id`` links the PHI-minimized family SMS
actually sent. ``status`` is 'sent' (a family contact was notified) or 'no_contact' (no
family registered — surfaced to operators, FR-013).
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0025"
down_revision: str | None = "0024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE family_reports (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            elder_id UUID NOT NULL REFERENCES elders(id),
            period_month DATE NOT NULL,
            calls_completed INTEGER NOT NULL DEFAULT 0,
            metrics JSONB NOT NULL DEFAULT '{}',
            narrative TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'sent',
            sms_message_id UUID REFERENCES sms_messages(id) ON DELETE SET NULL,
            model_version TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_family_reports_elder_period UNIQUE (elder_id, period_month),
            CONSTRAINT ck_family_reports_status CHECK (status IN ('sent', 'no_contact'))
        )
        """
    )
    op.execute(
        "CREATE INDEX idx_family_reports_elder ON family_reports (elder_id, period_month DESC)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS family_reports")
